import { environment } from "src/environments/environment";

export const API_ROUTES={
    Account:{
        login:`${environment.baseURl}/company/login`,
        signup:`${environment.baseURl}/company/signup`,
        otpSendPhone:`${environment.baseURl}/company/otp/send`,
        chooseInterest:`${environment.baseURl}/company/add-interest`,
        verifyOTP:`${environment.baseURl}/company/otp/verify`,
        getIndustry:`${environment.baseURl}/company/industry/get`,
        getCategory:`${environment.baseURl}/company/get/category/category1`,
        getsubCategory:`${environment.baseURl}/company/get/category/category2`,
        industriesserve:`${environment.baseURl}/company/get/category/categoryL4`,
        subActivtiyL:`${environment.baseURl}/company/get/category/categoryL5`,
        getInterest:`${environment.baseURl}/company/interest/get`,
        loginOtp:`${environment.baseURl}/company/login/otp`,
        forgotPasword:`${environment.baseURl}/company/forget-password`,
        resetPassword:`${environment.baseURl}/company/reset-password`,
        editPhoneOrEmail: `${environment.baseURl}/company/edit-phone-email`,
        socialLogin: `${environment.baseURl}/company/login/social`,
        gstVerification: `${environment.baseURl}/company/verify-gst`,
        bannerList: `${environment.baseURl}/company/banner/list`
    },
    More:{
        moreDetails:`${environment.baseURl}/company/get/profile`,
        editProfile:`${environment.baseURl}/company/update/profile`,
        changepic:`${environment.baseURl}/company/update/picture`,
        changePassword:`${environment.baseURl}/company/update-password`,
        addUser:`${environment.baseURl}/company/user/register`,
        userList:`${environment.baseURl}/company/get/user/list`,
        userDetails:`${environment.baseURl}/company/get/user/detail`,
        userDelete:`${environment.baseURl}/company/deactivate/user`,
        getInterest:`${environment.baseURl}/company/interest/get`,
        selectedInterest: `${environment.baseURl}/company/interest/getById`,
        updatePicture: `${environment.baseURl}/company/update/picture`,
        updateInterest: `${environment.baseURl}/company/update/Interest`
    },
    Post:{
        createPost:`${environment.baseURl}/company/createPost`,
        createPostById: `${environment.baseURl}/company/post/list/getById`,
        updatePost:`${environment.baseURl}/company/post/update`,
        deletePost:`${environment.baseURl}/company/post/delete`,
        myPost:`${environment.baseURl}/company/post/list`,
        likePost:`${environment.baseURl}/company/post/like`,
        postDetail:`${environment.baseURl}/company/post/list/detail`,
        postComment:`${environment.baseURl}/company/post/comment`,
        replyComment:`${environment.baseURl}/company/post/comment/reply`,
        sharepost:`${environment.baseURl}/company/post/share`,
        postCommentList:`${environment.baseURl}/company/comment/list`,
        likeComment:`${environment.baseURl}/company/post/comment/like`,
        editComment: `${environment.baseURl}/company/post/comment-edit`,
        deleteComment: `${environment.baseURl}/company/comment/delete`
    },
    Home:{
        homeListing:`${environment.baseURl}/company/home/list`
    },
    chat:{
        intrestedUserList:`${environment.baseURl}/company/interested-user`,
        getRoomId:`${environment.baseURl}/company/chat-rooms`
    },
    PurchaseOrder:{
        getCompanyList:`${environment.baseURl}/company/get/company-detail`,
        getBusinessActivities:`${environment.baseURl}/company/industry/get`,
        getIndustries:`${environment.baseURl}/company/get/category/category1`,
        getProductSubCategoryList:`${environment.baseURl}/company/get/category/category2`,
        getProductTypeList:`${environment.baseURl}/company/get/category/category3`,
        getProductSubTypeList:`${environment.baseURl}/company/get/category/category4`,
        getBrandList:`${environment.baseURl}/company/product/brand`,
        createOrderForPurchase:`${environment.baseURl}/company/create/purchase-order`,
        OtherOrderList:`${environment.baseURl}/company/get/purchase-order-other-list`,
        PurchaseOrderList:`${environment.baseURl}/company/get/purchase-order-list`,
        PurchaseOrderDetail:`${environment.baseURl}/company/get/purchase-order-detail`,
        deletePurchaseOrder:`${environment.baseURl}/company/delete/purchase`,
        rejectPurchaseOrder:`${environment.baseURl}/company/rejected-order`,
        acceptPurchaseOrder:`${environment.baseURl}/company/accepted-order`,
        updatePurchaseOrder:`${environment.baseURl}/company/update/purchase`,
        getVersionList:`${environment.baseURl}/company/get/version-list`,
        getVersion1detail:`${environment.baseURl}/company/get/version1detail`,
    },
    Projects:{
        createProjects:`${environment.baseURl}/company/project/create`,
        updateProjects:`${environment.baseURl}/company/project/update`,
        projectsDetail:`${environment.baseURl}/company/project/details`,
        projectsList:`${environment.baseURl}/company/project/list`,
        deleteProject:`${environment.baseURl}/company/project/delete`,
    },
    Machine:{
        machineList:`${environment.baseURl}/company/machine_instrument/list`,
        createMachine:`${environment.baseURl}/company/machine_instrument/create`,
        machineDetail:`${environment.baseURl}/company/machine_instrument/details`,
        updateMachine:`${environment.baseURl}/company/machine_instrument/update`,
        // getMachine:`${environment.baseURl}/company/machiene/details`,
        deleteMachine:`${environment.baseURl}/company/machine_instrument/delete`,
        instrumentList:`${environment.baseURl}/company/machine_instrument/list`
   
},
    MyRequirements: {
        industryList:`${environment.baseURl}/company/industry/get`,
        industryCategory1:`${environment.baseURl}/company/get/category/category1`,
        industryCategory2: `${environment.baseURl}/company/get/category/category2`,
        industryCategory3: `${environment.baseURl}/company/get/category/category3`,
        createRequirement: `${environment.baseURl}/company/requirement/create`,
        getRequirementDetail: `${environment.baseURl}/company/requirement/getDetail`,
        updateRequirement: `${environment.baseURl}/company/requirement/update`,
        getAllRequirementList: `${environment.baseURl}/company//requirement/getAllList`,
        deleteRequirement: `${environment.baseURl}/company/requirement/delete`,
        interestedUsers: `${environment.baseURl}/company/interested-user`,
        saveRequirement: `${environment.baseURl}/company/save/requirement`,
        showinterest:`${environment.baseURl}/company/requirement/like/unlike`,
        report:`${environment.baseURl}/company/report`,
        SaveList: `${environment.baseURl}/company/requirement/saveList`,
        unSave: `${environment.baseURl}/company/unsave/requirement`
    },

FeatureProduct:{
    addProduct:`${environment.baseURl}/company/featuredproduct/create`,
    productList:`${environment.baseURl}/company/product/list`,
    productDetails:`${environment.baseURl}/company/product/details`,
    productupdate:`${environment.baseURl}/company/product/update`,
    deleteProduct:`${environment.baseURl}/company/product/delete`
},
Marketplace:{
    addProduct:`${environment.baseURl}/company/product/create`,
    businessActivity:`${environment.baseURl}/company/industry/get`,
    catagory_1:`${environment.baseURl}/company/get/category/category1`,
    catagory_2:`${environment.baseURl}/company/get/category/category2`,
    catagory_3:`${environment.baseURl}/company/get/category/category3`,
    catagory_4:`${environment.baseURl}/company/get/category/category4`,
    brand:`${environment.baseURl}/company/product/brand`,
    mymarketproductList:`${environment.baseURl}/company/product/getList`,
    updateProduct:`${environment.baseURl}/company/update/product`,
    productDetails:`${environment.baseURl}/company/product/getDetails`,
    deleteProduct:`${environment.baseURl}/company/delete/product`,
    shareToMarketPlace: `${environment.baseURl}/company/product/share-to-marketplace`,
    marketPlaceList: `${environment.baseURl}/company/product/market-place/list`,
    myMarketPlaceList: `${environment.baseURl}/company/product/my-market-place/list`,
    showInterest: `${environment.baseURl}/company/product/interest`
},
customers:{
    addcustomer:`${environment.baseURl}/company/create/customerInfo`,
    blockedCustomers: `${environment.baseURl}/company/customer/BlockedList`,
    unblockCustomer: `${environment.baseURl}/company/customer/UnBlocked`,
    customerDetail: `${environment.baseURl}/company/customer/Details`,
    updateCustomer:`${environment.baseURl}/company/update/customer`,
    customerDetails:`${environment.baseURl}/company/customer/Details`,
    getState:`${environment.baseURl}/company/city-state`,
    getBuyer:`${environment.baseURl}/company/customer/buyerSeller/List`,
    blockCustomer: `${environment.baseURl}/company/customer/Blocked`,
    paymentDetails:`${environment.baseURl}/company/customer/payments`,
    orderDetails: `${environment.baseURl}/company/customer/orders`,
    getSeller:`${environment.baseURl}/company/customer/buyerSeller/List`,
},
Transactions:{
    create:`${environment.baseURl}/company/create/transaction`,
    transactionList: `${environment.baseURl}/company/get/transaction-list`,
    deleteTransaction: `${environment.baseURl}/company/delete/transaction`,
    detailTransaction: `${environment.baseURl}/company/get/transaction-detail`,
    updateTransaction: `${environment.baseURl}/company/update/transaction`,
    stats: `${environment.baseURl}/company/get/stasticsList`,
    addExpense:`${environment.baseURl}/company/create/expenses`,
    updateExpense:`${environment.baseURl}/company/update/expenses`,
    expenseDetails:`${environment.baseURl}/company/get/expenses-detail`,
    expenseList:`${environment.baseURl}/company/get/expenses-list`,
    deleteExpense:`${environment.baseURl}/company/delete/expenses`,
},

SalesOrder: {
    salesOrderList:`${environment.baseURl}/company/get/sales-order-list`,
    delete: `${environment.baseURl}/company/delete/sales`,
    getCompanyList:`${environment.baseURl}/company/get/company-detail`,
    getBusinessActivities:`${environment.baseURl}/company/industry/get`,
    getIndustries:`${environment.baseURl}/company/get/category/category1`,
    getProductSubCategoryList:`${environment.baseURl}/company/get/category/category2`,
    getProductTypeList:`${environment.baseURl}/company/get/category/category3`,
    getProductSubTypeList:`${environment.baseURl}/company/get/category/category4`,
    getBrandList:`${environment.baseURl}/company/product/brand`,
    createOrderForSales:`${environment.baseURl}/company/create/sales-order`,
    OtherOrderList:`${environment.baseURl}/company/get/sales-order-other-list`,
    SalesOrderList:`${environment.baseURl}/company/get/sales-order-list`,
    SalesOrderDetail:`${environment.baseURl}/company/get/sales-order-detail`,
    PurchaseOrderDetail:`${environment.baseURl}/company/get/purchase-order-detail`,
    customerPurchaseList:`${environment.baseURl}/company/get/company-wise-purchase-list`,
    updateSalesOrder:`${environment.baseURl}/company/update/sales-order`,
    requeustToEdit:`${environment.baseURl}/company/request-to-edit`,
    acceptOrder:`${environment.baseURl}/company/accepted-order`,
    deletePurchaseOrder: `${environment.baseURl}/company/delete/purchase`,
},
ActivityLogs: {
    logs:`${environment.baseURl}/company/get/activity-log-list`,
},
Dashboard: {
    logs:`${environment.baseURl}/company/get/stasticsList`,
}

}
